algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
var
   base, altura, area : real
inicio
      escreva("Informe a base do triângulo: ")
      leia(base)
      
      escreva("Informe a altura do triângulo: ")
      leia(altura)
      
      area := (base * altura)/2

      escreva("A área do triângulo é igual á : ", area)
fimalgoritmo