algoritmo "semnome"
var
   salarioFixo, bonusPorVenda, salarioTotal, valorVendas : real
   SoftwaresVendidos : inteiro
inicio
      salarioFixo := 500,00
      bonusPorVenda := 50,00
      SoftwaresVendidos := 20
      valorVendas := (bonusPorVenda * softwaresVendidos)
      salarioTotal := (valorVendas + salarioFixo)

      escreva("Nosso vendedor de softwares vendeu 50 softwares esse mês, o salário total dele foi de: ",salarioTotal )

      
      
      
fimalgoritmo