algoritmo "semnome"
var
    nome : caractere
    idade : inteiro
    salario : real
inicio
      escreva("Informe o seu nome por favor: ")
      leia(nome)
      
      escreva("Informe sua idade por favor: ")
      leia(idade)
      
      escreva("Informe o seu salário por favor: ")
      leia(salario)
      
      escreval("Nome: ",nome)
      escreval("idade ", idade," anos")
      escreva("Salário: ", salario)
fimalgoritmo