algoritmo "semnome"
var
   nota1, nota2, nota3, nota4, media : real
inicio
       escreva("Digite a primeira nota: ")
       leia(nota1)
       
       escreva("Digite a segunda nota: ")
       leia(nota2)
       
       escreva("Digite a terceira nota: ")
       leia(nota3)
       
       escreva("Digita a quarta nota: ")
       leia(nota4)
       
       media:= (nota1 + nota2 + nota3+ nota4)/4
       
       escreva("A média das notas é igual á" ,media)
       
fimalgoritmo